dist: xenial
language: python
python:
  - "3.6"
  - "3.7"

install: 
  - pip3 install --upgrade pip
  - pip3 install -r requirements.txt

script:
  - python3 DRIVER_dyedot.py -p VCF/ -o ./Test/test
  - python3 DRIVER_dyedot.py
  - python3 DRIVER_dyedot.py -r True
